services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "statsdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  stats-server:
    build:
      context: ./ewm-stats-service/stats-server  # ← Изменено: указываем на подпапку с src и pom.xml
      dockerfile: Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9090

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: ewm
      POSTGRES_PASSWORD: ewm
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ewm", "-d", "ewm-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-main-service:
    build:
      context: ./ewm-main-service
      dockerfile: Dockerfile
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      SPRING_DATASOURCE_USERNAME: ewm
      SPRING_DATASOURCE_PASSWORD: ewm
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      STATS_SERVER_URL: http://stats-server:9090
      SERVER_PORT: 8080
#      TZ: Europe/Moscow
    depends_on:
      - ewm-db
      - stats-server
    volumes:
      - ./ewm-main-service.log:/app/logs/ewm-main-service.log

networks:
  default:
    driver: bridge