version: '3.9'

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "statsdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  stats-server:
    build:
      context: .                  # теперь контекст — корень репозитория
      dockerfile: Dockerfile      # используем Dockerfile из корня
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9090

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:16.1
